"""
calibrated_constants.py
Auto-generated by calibration/calibrate_env.py

Decomposed formula:
  total_ms = submit_overhead + container_startup
           + α * workload_proxy * (1 + β * cpu_during/100)
           + poll_overhead

  workload_proxy_ms = clamp(deadline_ms/1000 * 0.5, 1, 15)
                    * (cpu_requirement / 30) * 1000
"""

EXEC_CALIBRATION = {'cloud': {'alpha': 1.0407211462802275, 'beta': -0.004567452589129551, 'r2': 0.00040658168648655124, 'rmse_ms': 475.7564515808978, 'n': 80}, 'edge_1': {'alpha': 0.9996430959361877, 'beta': 0.028307213642111938, 'r2': 0.012583768789789507, 'rmse_ms': 483.4098022292106, 'n': 78}, 'edge_2': {'alpha': 1.0112201608611744, 'beta': 0.03344657331821118, 'r2': 0.017536920278206303, 'rmse_ms': 467.82531250007395, 'n': 97}}

OVERHEAD_CALIBRATION = {'cloud': {'submit_overhead_ms': 487.5, 'container_startup_ms': 900.0, 'poll_overhead_ms': 3128.75}, 'edge_1': {'submit_overhead_ms': 179.48717948717947, 'container_startup_ms': 1525.6410256410256, 'poll_overhead_ms': 3468.7051282051284}, 'edge_2': {'submit_overhead_ms': 247.42268041237114, 'container_startup_ms': 1556.701030927835, 'poll_overhead_ms': 3493.536082474227}}


def workload_proxy_ms(cpu_requirement: float, deadline_ms: float) -> float:
    duration_s = max(1.0, min(deadline_ms / 1000.0 * 0.5, 15.0))
    return duration_s * (cpu_requirement / 30.0) * 1000.0


def predict_total_ms(role: str, cpu_requirement: float,
                     deadline_ms: float, cpu_during_exec: float) -> float:
    ec = EXEC_CALIBRATION.get(role)
    oh = OVERHEAD_CALIBRATION.get(role)
    if ec is None or oh is None:
        return 50.0  # fallback
    wp = workload_proxy_ms(cpu_requirement, deadline_ms)
    exec_pred = ec['alpha'] * wp * (1 + ec['beta'] * cpu_during_exec / 100)
    return (oh['submit_overhead_ms'] + oh['container_startup_ms']
            + exec_pred + oh['poll_overhead_ms'])
