"""
calibrated_constants.py
Auto-generated by calibration/calibrate_env.py

Decomposed formula:
  total_ms = submit_overhead + container_startup
           + α * workload_proxy * (1 + β * cpu_during/100)
           + poll_overhead

  workload_proxy_ms = clamp(deadline_ms/1000 * 0.5, 1, 15)
                    * (cpu_requirement / 30) * 1000
"""

EXEC_CALIBRATION = {'cloud': {'alpha': 0.3441643394484672, 'beta': 1.212042539126605, 'r2': 0.6884230951027233, 'rmse_ms': 966.6325269763022, 'n': 55}, 'edge_1': {'alpha': 0.8568036767638868, 'beta': 0.4340517999632362, 'r2': 0.13537699938480474, 'rmse_ms': 2858.8460300495476, 'n': 66}, 'edge_2': {'alpha': 0.8659150064963446, 'beta': 0.18973736694966825, 'r2': 0.02753382652814551, 'rmse_ms': 2921.029021363691, 'n': 82}}

OVERHEAD_CALIBRATION = {'cloud': {'submit_overhead_ms': 618.1818181818181, 'container_startup_ms': 709.0909090909091, 'poll_overhead_ms': 3148.6363636363635}, 'edge_1': {'submit_overhead_ms': 166.66666666666666, 'container_startup_ms': 1196.969696969697, 'poll_overhead_ms': 3521.8939393939395}, 'edge_2': {'submit_overhead_ms': 317.0731707317073, 'container_startup_ms': 1256.0975609756097, 'poll_overhead_ms': 3484.987804878049}}


def workload_proxy_ms(cpu_requirement: float, deadline_ms: float) -> float:
    duration_s = max(1.0, min(deadline_ms / 1000.0 * 0.5, 15.0))
    return duration_s * (cpu_requirement / 30.0) * 1000.0


def predict_total_ms(role: str, cpu_requirement: float,
                     deadline_ms: float, cpu_during_exec: float) -> float:
    ec = EXEC_CALIBRATION.get(role)
    oh = OVERHEAD_CALIBRATION.get(role)
    if ec is None or oh is None:
        return 50.0  # fallback
    wp = workload_proxy_ms(cpu_requirement, deadline_ms)
    exec_pred = ec['alpha'] * wp * (1 + ec['beta'] * cpu_during_exec / 100)
    return (oh['submit_overhead_ms'] + oh['container_startup_ms']
            + exec_pred + oh['poll_overhead_ms'])
