"""
calibrated_constants.py
Auto-generated by calibration/calibrate_env.py

Decomposed formula:
  total_ms = submit_overhead + container_startup
           + α * workload_proxy * (1 + β * cpu_during/100)
           + poll_overhead

  workload_proxy_ms = clamp(deadline_ms/1000 * 0.5, 1, 15)
                    * (cpu_requirement / 30) * 1000
"""

EXEC_CALIBRATION = {'cloud': {'alpha': 1.0370967926754322, 'beta': -0.030435851303708808, 'r2': 0.037514301978835984, 'rmse_ms': 370.8548279697976, 'n': 56}, 'edge_1': {'alpha': 0.9804388951905397, 'beta': 0.04533948553532539, 'r2': 0.04646453090674618, 'rmse_ms': 416.4479388178287, 'n': 73}, 'edge_2': {'alpha': 0.9935241870594481, 'beta': 0.0538549314330296, 'r2': 0.06698784356830267, 'rmse_ms': 450.26545791513007, 'n': 55}}

OVERHEAD_CALIBRATION = {'cloud': {'submit_overhead_ms': 142.85714285714286, 'container_startup_ms': 678.5714285714286, 'poll_overhead_ms': 3034.2678571428573}, 'edge_1': {'submit_overhead_ms': 2931.5068493150684, 'container_startup_ms': 1643.835616438356, 'poll_overhead_ms': 3518.6849315068494}, 'edge_2': {'submit_overhead_ms': 781.8181818181819, 'container_startup_ms': 1327.2727272727273, 'poll_overhead_ms': 3459.0}}


def workload_proxy_ms(cpu_requirement: float, deadline_ms: float) -> float:
    duration_s = max(1.0, min(deadline_ms / 1000.0 * 0.5, 15.0))
    return duration_s * (cpu_requirement / 30.0) * 1000.0


def predict_total_ms(role: str, cpu_requirement: float,
                     deadline_ms: float, cpu_during_exec: float) -> float:
    ec = EXEC_CALIBRATION.get(role)
    oh = OVERHEAD_CALIBRATION.get(role)
    if ec is None or oh is None:
        return 50.0  # fallback
    wp = workload_proxy_ms(cpu_requirement, deadline_ms)
    exec_pred = ec['alpha'] * wp * (1 + ec['beta'] * cpu_during_exec / 100)
    return (oh['submit_overhead_ms'] + oh['container_startup_ms']
            + exec_pred + oh['poll_overhead_ms'])